<a href="https://colab.research.google.com/github/Sachinsachin21/Deep_learning/blob/main/Tf_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a = tf.Variable([
    [3,4,5]
    ],dtype=tf.int32)
b = tf.Variable([
    [9,8,7]
    ], dtype=tf.int32)
a
b

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[9, 8, 7]], dtype=int32)>

In [3]:
c= tf.add(a,b)
c.numpy()

array([[12, 12, 12]], dtype=int32)

In [4]:
a = tf.constant(10)
b = tf.constant(20)
def f1():
    return tf.constant(a)
def f2():
    return tf.constant(b)
r = tf.cond(tf.greater(a,b),f1,f2)
r.numpy()

20

In [24]:
result = tf.Variable(np.zeros([11], dtype = np.int32))
result

<tf.Variable 'Variable:0' shape=(11,) dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)>

In [6]:
def run():
  i = tf.constant(0, dtype = tf.int32)
  while tf.less_equal(i, 10):
    result.assign(i)
    i+=1
    run()

In [7]:
result.numpy()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [8]:
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import fashion_mnist as fm

In [9]:
(x_train,y_train),(x_test,y_test) = fm.load_data()

4422102/4422102 [==============================] - 1s 0us/step


In [10]:
def prepos(x,y):
    x = tf.cast(x,tf.float32)/255.0
    y = tf.cast(y,tf.int64)
    return x,y
def create_ds(xs,ys,n_classes = 10):
  ys = tf.one_hot(ys,n_classes)
  return tf.data.Dataset.from_tensor_slices((xs,ys))

In [11]:
td = create_ds(x_train,y_train)
vd = create_ds(x_test,y_test)

In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Reshape,Dense

In [13]:
model = Sequential([
    Reshape(target_shape=(28*28, ),input_shape=(28,28,1)),
    Dense(units = 36,activation='relu'),
    Dense(units = 64,activation='relu'),
    Dense(units = 128,activation='relu'),
    Dense(units = 10,activation='softmax')
])

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 reshape (Reshape)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 36)                28260     
                                                                 
 dense_1 (Dense)             (None, 64)                2368      
                                                                 
 dense_2 (Dense)             (None, 128)               8320      
                                                                 
 dense_3 (Dense)             (None, 10)                1290      
                                                                 
Total params: 40238 (157.18 KB)
Trainable params: 40238 (157.18 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [26]:
model.compile(optimizer='adam',
              loss= tf.losses.CategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
model.predict(x_train[0:1])

1/1 [==============================] - 0s 122ms/step


array([[0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 3.564096e-11,
        0.000000e+00, 1.000000e+00]], dtype=float32)

In [16]:
tf.ones(shape=(5,10))

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [17]:
tf.zeros(shape=(5,10))

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [18]:
tf.eye(3,3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [19]:
tf.random.normal(shape=(3,3),mean=3,stddev=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.3206558,  6.2364035, -1.0117359],
       [ 2.2834475,  2.3563452,  3.450149 ],
       [ 4.287799 , -1.863987 ,  4.1797047]], dtype=float32)>

In [20]:
tf.random.uniform(shape=(3,3),minval=0,maxval=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.6155914 , 0.91165614, 0.23272085],
       [0.9561615 , 0.9131675 , 0.05722809],
       [0.8115468 , 0.24742329, 0.5378512 ]], dtype=float32)>

In [21]:
a = tf.range(21)

In [22]:
tf.random.set_seed(21)

In [23]:
tf.cast(a,tf.float32)

<tf.Tensor: shape=(21,), dtype=float32, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.], dtype=float32)>